title: The APL Show
description: Inspired by Ken Iversonâ€™s paper ğ˜•ğ˜°ğ˜µğ˜¢ğ˜µğ˜ªğ˜°ğ˜¯ ğ˜¢ğ˜´ ğ˜¢ ğ˜›ğ˜°ğ˜°ğ˜­ ğ˜°ğ˜§ ğ˜›ğ˜©ğ˜°ğ˜¶ğ˜¨ğ˜©ğ˜µ, this podcast explores various aspects of notation, in the context of the APL programming language. ğ—¥ğ—¶ğ—°ğ—µğ—®ğ—¿ğ—± is an APL instructor at Dyalog Ltd, has taught APL at multiple schools, and created an online self-study course. ğ—”ğ—±ğ—®Ìğ—º launched the ğ˜ˆğ˜—ğ˜“ ğ˜–ğ˜³ğ˜¤ğ˜©ğ˜¢ğ˜³ğ˜¥ chat room and ğ˜ˆğ˜—ğ˜“ğ˜¤ğ˜¢ğ˜³ğ˜µ, and is the co-author of the ğ˜ˆğ˜—ğ˜“ ğ˜Šğ˜¶ğ˜­ğ˜µğ˜ªğ˜·ğ˜¢ğ˜µğ˜ªğ˜°ğ˜¯ğ˜´ book. Both are ğ˜‹ğ˜ºğ˜¢ğ˜­ğ˜°ğ˜¨ ğ˜“ğ˜µğ˜¥ employees, regular hosts of Dyalog webinars, and recurring panellists on the ğ˜ˆğ˜³ğ˜³ğ˜¢ğ˜º ğ˜Šğ˜¢ğ˜´ğ˜µ podcast. 
author: AdÃ¡m Brudzewsky & Richard Park
email: contact@apl.show
lang: en
copyright: "&#x2117; &amp; &#xA9; 2022â€“2023"
logo: logo.svg
# baseurl: "/" # the subpath of your site, e.g. /blog
# url: "https://apl.show" # the base hostname & protocol for your site, e.g. http://example.com

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
